/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:fd0ed6e6-5efd-4c80-8ab6-d08462212162",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_LlxD473XL",
    "aws_user_pools_web_client_id": "1cfk5t8jjuc187amrh9aita4ir",
    "oauth": {
        "domain": "dev-triggers-blog-domain.auth.eu-central-1.amazoncognito.com"
    },
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 10,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_user_files_s3_bucket": "dev-cognito-triggers-blog-users-bucket",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
